[package]
name = "ue-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
hard-xml = "1.15.0"
uuid = "1.2"
sha2 = "0.10"
url = "2"

[dependencies.omaha]
path = "omaha"

[workspace]

members = [
    "omaha",
]
