[package]
name = "ue-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
uuid = "1.2"
sha2 = "0.10"
url = "2"

env_logger = "0.10"
log = "0.4"
argh = "0.1"
globset = "0.4"
protobuf = "3.2.0"

[dependencies.hard-xml]
path = "vendor/hard-xml"

[dependencies.omaha]
path = "omaha"

[dependencies.update-format-crau]
path = "update-format-crau"

[workspace]
members = [
    "omaha",
    "update-format-crau"
]

[[bin]]
name = "crau_verify"
path = "test/crau_verify.rs"
