name: "Run CI"
on:
  pull_request:

jobs:
  build-test:
    name: Build and test ue-rs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - name: Rustfmt Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check
      - name: Build ue-rs
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace
      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
